{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2020-22916",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2023-09-12T15:45:11.103736",
        "dateReserved": "2020-08-13T00:00:00",
        "datePublished": "2023-08-22T00:00:00"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2023-09-12T15:45:11.103736"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue discovered in XZ 5.2.5 allows attackers to cause a denial of service via decompression of a crafted file. NOTE: the software maintainers are unable to reproduce this as of 2023-09-12 because the example crafted file is temporarily offline."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "n/a",
                    "versions": [
                        {
                            "version": "n/a",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://tukaani.org/xz/"
                },
                {
                    "url": "https://github.com/snappyJack/CVE-request-XZ-5.2.5-has-denial-of-service-vulnerability"
                },
                {
                    "url": "https://github.com/tukaani-project/xz/issues/61"
                },
                {
                    "url": "https://security-tracker.debian.org/tracker/CVE-2020-22916"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2234987"
                },
                {
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1214590"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "text",
                            "lang": "en",
                            "description": "n/a"
                        }
                    ]
                }
            ]
        }
    }
}